package com.example.catdogincompose.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a phrase stored in the local database.
 *
 * This data class is annotated with Room's `@Entity` annotation, making it a table in the database.
 * Each instance of this class represents a single row in the "phrases" table.
 *
 * @property id The unique identifier for the phrase. It's auto-generated by Room.
 * @property text The actual text content of the phrase.
 * @property type The type or category of the phrase (e.g., "greeting", "farewell", "question").
 */
@Entity(tableName = "phrases")
data class PhraseEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val text: String,
    val type: String
)